apiVersion: v1
entries:
  prometheus-acm-exporter:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-01-17T06:05:48.192886538Z"
    description: A Helm chart for Prometheus ACM Certificate Exporter
    digest: bb5832a4caaf4f12a31e42deed7c01bcc6e988b35200364574d33a89297814a2
    keywords:
    - prometheus
    - acm
    - aws
    - exporter
    - metrics
    maintainers:
    - name: Prometheus ACM Certificate Exporter Contributors
    name: prometheus-acm-exporter
    type: application
    urls:
    - https://gbhosal.github.io/prometheus-acm-exporter/charts/prometheus-acm-exporter-0.1.0.tgz
    version: 0.1.0
generated: "2026-01-17T06:05:48.192253217Z"
