apiVersion: v1
entries:
  prometheus-acm-exporter:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-01-18T06:00:42.487627486Z"
    description: A Helm chart for Prometheus ACM Certificate Exporter
    digest: b65045016b4223a5c8af89fe425922f0e731562de1faee97ef59482511070ce5
    keywords:
    - prometheus
    - acm
    - aws
    - exporter
    - metrics
    maintainers:
    - name: Prometheus ACM Certificate Exporter Contributors
    name: prometheus-acm-exporter
    type: application
    urls:
    - https://gbhosal.github.io/prometheus-acm-exporter/charts/prometheus-acm-exporter-1.0.0.tgz
    version: 1.0.0
generated: "2026-01-18T06:00:42.487071203Z"
