apiVersion: v1
entries:
  prometheus-acm-exporter:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-01-18T06:05:46.581852373Z"
    description: A Helm chart for Prometheus ACM Certificate Exporter
    digest: b6667a8b3227afaa4c5141c73bb7057837e7b6fce152ed937f7ef7dfbc1d0c50
    keywords:
    - prometheus
    - acm
    - aws
    - exporter
    - metrics
    maintainers:
    - name: Prometheus ACM Certificate Exporter Contributors
    name: prometheus-acm-exporter
    type: application
    urls:
    - https://gbhosal.github.io/prometheus-acm-exporter/charts/prometheus-acm-exporter-1.0.0.tgz
    version: 1.0.0
generated: "2026-01-18T06:05:46.581255132Z"
