apiVersion: v1
entries:
  prometheus-acm-exporter:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-01-17T06:14:33.412435012Z"
    description: A Helm chart for Prometheus ACM Certificate Exporter
    digest: dca00e892c038fc4ca678f6510aaba781ec2e33039fea365ec4fa71c5968329f
    keywords:
    - prometheus
    - acm
    - aws
    - exporter
    - metrics
    maintainers:
    - name: Prometheus ACM Certificate Exporter Contributors
    name: prometheus-acm-exporter
    type: application
    urls:
    - https://gbhosal.github.io/prometheus-acm-exporter/charts/prometheus-acm-exporter-1.0.0.tgz
    version: 1.0.0
generated: "2026-01-17T06:14:33.410774054Z"
