apiVersion: v1
entries:
  prometheus-acm-exporter:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-01-17T05:46:19.220763479Z"
    description: A Helm chart for Prometheus ACM Certificate Exporter
    digest: 0c0055297969c60f82a41a33e1144c97005e9b51d605e3bc0123f79379e6d4a9
    keywords:
    - prometheus
    - acm
    - aws
    - exporter
    - metrics
    maintainers:
    - name: Prometheus ACM Certificate Exporter Contributors
    name: prometheus-acm-exporter
    type: application
    urls:
    - https://gbhosal.github.io/prometheus-acm-exporter/charts/prometheus-acm-exporter-0.1.0.tgz
    version: 0.1.0
generated: "2026-01-17T05:46:19.220189902Z"
