apiVersion: v1
entries:
  prometheus-acm-exporter:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-01-17T06:09:36.259212387Z"
    description: A Helm chart for Prometheus ACM Certificate Exporter
    digest: 31b216c0f2d92bcb9dac48cd0cbbbaec0310ca7300ad4110ce5866067c63c235
    keywords:
    - prometheus
    - acm
    - aws
    - exporter
    - metrics
    maintainers:
    - name: Prometheus ACM Certificate Exporter Contributors
    name: prometheus-acm-exporter
    type: application
    urls:
    - https://gbhosal.github.io/prometheus-acm-exporter/charts/prometheus-acm-exporter-0.1.0.tgz
    version: 0.1.0
generated: "2026-01-17T06:09:36.258618457Z"
