apiVersion: v1
entries:
  prometheus-acm-exporter:
  - apiVersion: v2
    appVersion: v1.1.0
    created: "2026-02-03T11:10:26.099782414Z"
    description: A Helm chart for Prometheus ACM Certificate Exporter
    digest: 5a5f329491e117faf6ec6a9fc0ccd3183609451d033cc3aa88aa1ea11c4e3f51
    keywords:
    - prometheus
    - acm
    - aws
    - exporter
    - metrics
    maintainers:
    - name: Prometheus ACM Certificate Exporter Contributors
    name: prometheus-acm-exporter
    type: application
    urls:
    - https://gbhosal.github.io/prometheus-acm-exporter/charts/prometheus-acm-exporter-1.1.0.tgz
    version: 1.1.0
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-02-03T11:10:26.099285241Z"
    description: A Helm chart for Prometheus ACM Certificate Exporter
    digest: bea6771e7b45c5a79d79a16e18db3b9c3e85c4e61b7abd4528b46ed343ec6265
    keywords:
    - prometheus
    - acm
    - aws
    - exporter
    - metrics
    maintainers:
    - name: Prometheus ACM Certificate Exporter Contributors
    name: prometheus-acm-exporter
    type: application
    urls:
    - https://gbhosal.github.io/prometheus-acm-exporter/charts/prometheus-acm-exporter-1.1.0-beta.1.tgz
    version: 1.1.0-beta.1
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-02-03T11:10:26.098727226Z"
    description: A Helm chart for Prometheus ACM Certificate Exporter
    digest: 4d2f1da3ef6beb322b8540473ec54edce56ecbeaca915e5cbb5af0e6cf5f7e1f
    keywords:
    - prometheus
    - acm
    - aws
    - exporter
    - metrics
    maintainers:
    - name: Prometheus ACM Certificate Exporter Contributors
    name: prometheus-acm-exporter
    type: application
    urls:
    - https://gbhosal.github.io/prometheus-acm-exporter/charts/prometheus-acm-exporter-1.0.0.tgz
    version: 1.0.0
generated: "2026-02-03T11:10:26.098048236Z"
