apiVersion: v1
entries:
  prometheus-acm-exporter:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-01-18T06:31:32.083816839Z"
    description: A Helm chart for Prometheus ACM Certificate Exporter
    digest: 4d2f1da3ef6beb322b8540473ec54edce56ecbeaca915e5cbb5af0e6cf5f7e1f
    keywords:
    - prometheus
    - acm
    - aws
    - exporter
    - metrics
    maintainers:
    - name: Prometheus ACM Certificate Exporter Contributors
    name: prometheus-acm-exporter
    type: application
    urls:
    - https://gbhosal.github.io/prometheus-acm-exporter/charts/prometheus-acm-exporter-1.0.0.tgz
    version: 1.0.0
generated: "2026-01-18T06:31:32.083218143Z"
