apiVersion: v1
entries:
  prometheus-acm-exporter:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-01-18T05:30:38.508999099Z"
    description: A Helm chart for Prometheus ACM Certificate Exporter
    digest: 8949666f9599ac0e6b05269790b688c43e3ee79f770d857573d748c3f018bd75
    keywords:
    - prometheus
    - acm
    - aws
    - exporter
    - metrics
    maintainers:
    - name: Prometheus ACM Certificate Exporter Contributors
    name: prometheus-acm-exporter
    type: application
    urls:
    - https://gbhosal.github.io/prometheus-acm-exporter/charts/prometheus-acm-exporter-1.0.0.tgz
    version: 1.0.0
generated: "2026-01-18T05:30:38.508363983Z"
