apiVersion: v1
entries:
  prometheus-acm-exporter:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-01-18T05:34:50.28168703Z"
    description: A Helm chart for Prometheus ACM Certificate Exporter
    digest: ab42f6ee7c3f87e6f6019305965916001ab878d0f4414bd6c4f5d1c90407e02f
    keywords:
    - prometheus
    - acm
    - aws
    - exporter
    - metrics
    maintainers:
    - name: Prometheus ACM Certificate Exporter Contributors
    name: prometheus-acm-exporter
    type: application
    urls:
    - https://gbhosal.github.io/prometheus-acm-exporter/charts/prometheus-acm-exporter-1.0.0.tgz
    version: 1.0.0
generated: "2026-01-18T05:34:50.280700134Z"
