apiVersion: v2
name: prometheus-acm-exporter
description: A Helm chart for Prometheus ACM Certificate Exporter
type: application
version: 1.1.0-beta.1
appVersion: "v1.0.1-alpha"
keywords:
  - prometheus
  - acm
  - aws
  - exporter
  - metrics
maintainers:
  - name: Prometheus ACM Certificate Exporter Contributors
